---
title: "BMEG424_Final Project"
output: html_document
date: "2025-04-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
We chose the study “Experimental Evolution Reveals Unifying Systems-Level Adaptations but Diversity Driving Genotypes” to investigate for our course project. The study investigates the evolution of six strains of Escherichia Coli subjected to adaptive laboratory evolution (ALE). The aim of this study was to characterize genotype-fitness maps of evolution for system-level properties, including metabolic and transcriptional regulatory networks. The authors took a multi-omic approach by studying the correlation between gene expression, gene mutation and metabolic flux. The goal was to uncover systems-level adaptations and identify consistent mutational patterns across a diverse genetic background. 

Our reanalysis will focus on processing the raw sequencing data from this study to confirm the reproducibility and robustness of the authors’ methodology. We chose this specific study due to its comprehensive coverage of core concepts in genomic data analysis, as well as the large amount of publicly available sequencing data. WE WILL IMPROVE AND LOOK FOR OVERSIGHTS. Our analysis will include quality control, genome indexing and paired end alignment using automated pipelines and workflows. 

Potential oversights:

No automated pipeline?
No mention of quality control?
No report of alignment stats?

